name: rexprt_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.2
  - r-base=3.6.3
  # Python packages
  - numpy=1.21.6
  - pandas
  - scipy
  - scikit-learn=1.1.3
  - matplotlib
  - seaborn
  - xgboost
  - category_encoders
  - multiprocess  # For parallel processing
  - pyyaml  # For YAML configuration parsing
  - pip
  # R packages
  - r-tidyverse
  - r-data.table
  - r-devtools
  - r-plyr
  # System libraries
  - wget
  - unzip
  - git
  - parallel  # For enhanced parallel processing
